#ifndef CONFIG_H
#define CONFIG_H

#define MAX_NUM_CLIENTS 5 // Must be > 1
#define MAX_BILLBOARDS 3
#define MAX_CLIENT_NAME_LENGTH 50
#define NUM_MAX_BILLBOARD_CHAR 50
#define CONFIG_PARSE_BUFFER_SIZE 256
#define LCD_TEXT_WIDTH 16
#define LCD_BUF_LEN 17
#define UPDATE_INIT_VAL 10000
#define MAIN_UPDATE_INTERVAL 10000UL
#define FIXED_UPDATE_INTERVAL 10000UL
#define SCROLL_UPDATE_INTERVAL 200UL
#define BLINK_UPDATE_INTERVAL 1000UL

#endif