#ifndef CONFIG_H
#define CONFIG_H

#define NUM_CLIENTS 5
#define NUM_MAX_BILLBOARD_CHAR 50
#define CONFIG_PARSE_BUFFER_SIZE 256
#define LCD_TEXT_WIDTH 16
#define LCD_BUF_LEN 17
#define UPDATE_INIT_VAL 10000

#endif